### ISSUE TITLE
Appcrash issue in Android  - surfaceTexture must not be null

### ISSUE THREAD

**Issue by flutter-developer2508** [DavidPerezP124/jwplayer_plugin#45]
Application gets crashed in Android, while user pressed back button and throws this error.

E/AndroidRuntime(16216): java.lang.IllegalArgumentException: surfaceTexture must not be null
E/AndroidRuntime(16216):        at android.view.Surface.<init>(Surface.java:198)
E/AndroidRuntime(16216):        at com.longtailvideo.jwplayer.player.d.a.c.a(SourceFile:31)
E/AndroidRuntime(16216):        at com.longtailvideo.jwplayer.player.d.b.f(SourceFile:49)
E/AndroidRuntime(16216):        at com.longtailvideo.jwplayer.player.d.b.b(SourceFile:63)
E/AndroidRuntime(16216):        at com.longtailvideo.jwplayer.player.c.a(SourceFile:439)
E/AndroidRuntime(16216):        at com.longtailvideo.jwplayer.core.providers.c.b(SourceFile:391)
E/AndroidRuntime(16216):        at com.longtailvideo.jwplayer.core.providers.c.stop(SourceFile:734)
E/AndroidRuntime(16216):        at com.longtailvideo.jwplayer.core.providers.b$$ExternalSyntheticLambda7.run(Unknown Source:2)
E/AndroidRuntime(16216):        at android.os.Handler.handleCallback(Handler.java:790)
E/AndroidRuntime(16216):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(16216):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(16216):        at android.app.ActivityThread.main(ActivityThread.java:7000)
E/AndroidRuntime(16216):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16216):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
E/AndroidRuntime(16216):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)

**Comment by Pavel-dnipro** [comment]
any updates on this? have this error and app crash on tap Play button
